[build-system]
requires = ["setuptools>=65", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "eigsep_observing"
version = "0.0.1"
description = "Control code for EIGSEP observing."
readme = "README.md"
license = {text = "MIT"}
authors = [{ name="Christian Hellum Bye", email="cbh@berkeley.edu" }]
requires-python = ">=3.9"
classifiers = [
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Topic :: Scientific/Engineering :: Astronomy",
]
dependencies = [
  "h5py",
  "numpy",
  "pyyaml",
  "flask",
  "picohost @ file:///home/eigsep/eigsep/pico-firmware/picohost"
  "fakeredis==2.23.5",
  "cmt_vna @ file:///home/eigsep/eigsep/CMT-VNA",
  "eigsep_corr @ file:///home/eigsep/eigsep/eigsep_corr",
]

[project.optional-dependencies]
dev = [
  "black",
  "flake8",
  "pyserial-mock",
  "pytest",
  "pytest-cov",
  "pytest-timeout",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"eigsep_observing" = ["config/*.yaml"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
addopts = [
  "--cov=src",
  "--cov-report=term-missing",
  "--cov-report=xml",
  "--junitxml=junit.xml",
  "-o junit_family=legacy",
  "--timeout=60",
]

[tool.black]
line-length = 79
