snap_ip: "10.10.10.12"
fpg_file: "eigsep_fengine_1g_v2_3_2024-07-08_1858.fpg"  # path to fpg file
fpg_version: [2, 3]  # major, minor
sample_rate: 500.0  # in MHz
nchan: 1024
use_ref: false  # use synth on snap to generate adc clock from 10 MHz ref
use_noise: false  # use digital noise instead of ADC data
adc_gain: 4
fft_shift: 0x015F
#corr_acc_len: 0x10000000  # 2**28 - increment corr_acc_cnt by ~1/second
corr_acc_len: 0x04000000  # 2**26 - increment corr_acc_cnt by ~4/second
corr_scalar: 512  # 2**9 - 8 bits after binary point so 2**9 = 1
corr_word: 4  # 4 bytes per word
acc_bins: 2
dtype: ">i4"  # big-endian int32
pol_delay:
  "01": 0
  "23": 0
  "45": 0
redis:
  host: localhost
  port: 6379
pairs: ["0", "1", "2", "3", "4", "5", "02", "04", "13", "15", "24", "35"]
# signal chain config
rf_chain:
  "snap_id": C000069
  "ants":
    "box":
      fem:
        id: "eigsep1"
      pam:
        id: 375
        num: 2  # closest to PWR button
        pol: N  # polarization channel
        atten: 8  # attenuation in dB
      snap:
        input: 0  # digital input 0
        label: N0  # label on SNAP
    "viv1":  # vivaldi 1 (center)
      fem:
        id: 12
        pol: E
      pam:
        id: 375
        num: 2
        pol: E
        atten: 8
      snap:
        input: 1
        label: E2
    "viv2_north":  # north vivaldi / north pol
      fem:
        id: 32
        pol: N
      pam:
        id: 377
        num: 1
        pol: N
        atten: 8
      snap:
        input: 2
        label: N4
    "viv2_south":  # north vivaldi / east pol
      fem:
        id: 32
        pol: E
      pam:
        id: 377
        num: 1
        pol: E
        atten: 8
      snap:
        input: 3
        label: E6
    "viv3_north":  # south vivaldi / north pol
      fem:
        id: 348
        pol: N
      pam:
        id: 376
        num: 0
        pol: N
        atten: 8
      snap:
        input: 4
        label: N8
    "viv3_south":  # south vivaldi / east pol
      fem:
        id: 348
        pol: E
      pam:
        id: 376
        num: 0
        pol: E
        atten: 8
      snap:
        input: 5
        label: E10
