# Configuration for EigsepFpga and observing with the SNAP correlator

default:
  snap_ip: "10.10.10.13"
  sample_rate: 500.0  # in MHz
  use_ref: true  # use synth on snap to generate adc clock
  use_noise: false  # use digital noise instead of ADC data
  fpg_file: null  # will be set dynamically from DATA_PATH
  fpg_version: [2, 3]  # major, minor
  adc_gain: 4.0
  fft_shift: 0x055
  corr_acc_len: 67108864  # 2**26 - increment corr_acc_cnt by ~4/second
  corr_scalar: 512  # 2**9 - 8 bits after binary point so 2**9 = 1
  corr_word: 4  # 4 bytes per word
  dtype: ["int32", ">"]  # dtype, endian
  acc_bins: 2
  pam_atten:
    0: [8, 8]
    1: [8, 8]
    2: [8, 8]
  pol_delay:
    "01": 0
    "23": 0
    "45": 0
  nchan: 1024
  save_dir: "/media/eigsep/T7/data"
  ntimes: 240  # number of times per file

dummy:
  snap_ip: ""
  sample_rate: 500.0
  use_ref: true
  use_noise: false
  fpg_file: ""
  fpg_version: [0, 0]
  adc_gain: 4.0
  fft_shift: 0x055
  corr_acc_len: 67108864
  corr_scalar: 512
  corr_word: 4
  dtype: ["int32", ">"]
  acc_bins: 2
  pam_atten:
    0: [8, 8]
    1: [8, 8]
    2: [8, 8]
  pol_delay:
    "01": 0
    "23": 0
    "45": 0
  nchan: 1024
  save_dir: "./test_data"
  ntimes: 240