# dummy_config file for running on a single machine

# IP addresses
rpi_ip: "localhost"
panda_ip: "localhost"
# corr filewriter
corr_save_dir: "/home/christian/Documents/research/eigsep/eigsep_observing/test_data"
corr_ntimes: 240
# switches
use_switches: true
switch_schedule:  # seconds per measurement
  RFANT: 0  # sky
  RFNOFF: 20  # load
  RFNON: 20  # noise source
# vna
use_vna: false
vna_interval: 10  # seconds between VNA measurements
vna_ip: "127.0.0.1"
vna_port: 5025
vna_timeout: 1  # in seconds
vna_settings:
  fstart: 1000000.0  # in Hz
  fstop: 250000000.0  # in Hz
  npoints: 1000
  ifbw: 100.0  # in Hz
  power_dBm:
    ant: 0.0
    rec: -40.0
vna_save_dir: "/home/christian/Documents/research/eigsep/eigsep_observing/test_s11_data"
# motor
use_motor: false
motor_interval: 1  # seconds between scans
motor_failure_retry_s: 0.5  # fast retry for tests
motor_scan: {}
