# High-level configuration for EIGSEP observations
# Sets switch schedules, sensors, and other high-level parameters

# IP addresses
rpi_ip: "10.10.10.10"
panda_ip: "10.10.10.12"
# sensors
sensors:
  imu_az:
    pico: "/dev/pico_imu_az"
    cadence: 1  # seconds between readings
  imu_el:
    pico: "/dev/pico_imu_el"
    cadence: 1
  therm:
    pico: "/dev/pico_therm"
    cadence: 1
  peltier:
    pico: "/dev/pico_peltier"
    cadence: 1
  lidar:
    pico: "/dev/pico_lidar"
    cadence: 1
# switches
switch_pico: "/dev/pico_switch"
switch_schedule:  # seconds per measurement
  sky: 3600
  load: 60
  noise: 60
# vna
use_vna: true
vna_interval: 3600  # seconds between VNA measurements
vna_ip: "127.0.0.1"
vna_port: 5025
vna_timeout: 1000  # in seconds
vna_settings:
  fstart: 1000000.0  # in Hz
  fstop: 250000000.0  # in Hz
  npoints: 1000
  ifbw: 100.0  # in Hz
  power:
    ant: 0.0
    rec: -40.0
vna_save_dir: "/media/eigsep/T7/data/s11_data"
