# High-level configuration for EIGSEP observations
# Sets switch schedules, sensors, and other high-level parameters

default:
  rpi_ip: "10.10.10.10"
  panda_ip: "10.10.10.12"
  sensors:
    imu_az: "/dev/pico_imu_az"
    imu_el: "/dev/pico_imu_el"
    therm: "/dev/pico_therm"
    peltier: "/dev/pico_peltier"
    lidar: "/dev/pico_lidar"
  switch_pico: "/dev/pico_switch"
  switch_schedule:
    vna: 1
    snap_repeat: 1200
    sky: 100
    load: 100
    noise: 100
  vna_ip: "127.0.0.1"
  vna_port: 5025
  vna_timeout: 1000  # in seconds
  vna_fstart: 1000000.0  # in Hz
  vna_fstop: 250000000.0  # in Hz
  vna_npoints: 1000
  vna_ifbw: 100.0  # in Hz
  vna_power:
    ant: 0.0
    rec: -40.0
  vna_save_dir: "/media/eigsep/T7/data/s11_data"