# High-level configuration for EIGSEP observations
# Sets switch schedules, picos, VNA settings, and other parameters

# IP addresses
rpi_ip: "10.10.10.10"
panda_ip: "10.10.10.11"
# picos
pico_config_file: "/home/eigsep/eigsep/pico-firmware/pico_config.json"
pico_app_mapping:  # app number to device mapping
  0: "motor"
  1: "peltier"
  2: "therm"
  3: "imu"
  4: "lidar"
  5: "switch"
# corr filewriter
corr_save_dir: "/media/eigsep/T7/data"
corr_ntimes: 240
# switches
use_switches: false
switch_schedule:  # seconds per measurement
  RFANT: 3600  # sky
  RFNOFF: 60  # load
  RFNON: 60  # noise source
# vna
use_vna: false
vna_interval: 3600  # seconds between VNA measurements
vna_ip: "127.0.0.1"
vna_port: 5025
vna_timeout: 1000  # in seconds
vna_settings:
  fstart: 1000000.0  # in Hz
  fstop: 250000000.0  # in Hz
  npoints: 1000
  ifbw: 100.0  # in Hz
  power_dBm:
    ant: 0.0
    rec: -40.0
vna_save_dir: "/media/eigsep/T7/data/s11_data"
